
.TH DUB-REMOVE-OVERRIDE "1"

.SH NAME

dub\-remove\-override \- remove existing package override

.SH SYNOPSIS

.B dub remove\-override
.I PACKAGE
.I VERSION\-SPEC
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Removes an override created previously with \fBadd\-override\fR\&.

.SH OPTIONS

Apart of the options listed below, this command also honours common options 
listed in \fIdub\fR(1)\&.

.TP
.B \-\-system
Register system\-wide instead of user\-wide\&.

.SH SEE ALSO

\fIdub\fR(1), \fIdub\-add\-override\fR(1), \fIdub\-list\-overrides\fR(1)
