
.TH DUB-LIST-OVERRIDES "1"

.SH NAME

dub\-list\-overrides \- print a list of overridden packages

.SH SYNOPSIS

.B dub list\-overrides
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Prints a list of all overridden packages added via \fBadd\-override\fR\&.

.SH OPTIONS

This command supports all of the common options listed in \fIdub\fR(1)\&.

.SH SEE ALSO

\fIdub\fR(1), \fIdub\-add\-override\fR(1), \fIdub\-remove\-override\fR(1)
