
.TH DUB-CLEAN-CACHES "1"

.SH NAME

dub\-clean\-caches \- clean cached metadata

.SH SYNOPSIS

.B dub clean\-caches
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Removes any cached metadata like the list of available packages and their
latest version\&.

.SH OPTIONS

This command supports all of the common options listed in \fIdub\fR(1)\&.

.SH SEE ALSO

\fIdub\fR(1)
