
.TH DUB-SEARCH "1"

.SH NAME

dub\-search \- search for packages

.SH SYNOPSIS

.B dub search
.I QUERY
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Search all specified DUB registries for packages matching query\&.

.SH OPTIONS

This command supports all of the common options listed in \fIdub\fR(1)\&.

.SH SEE ALSO

\fIdub\fR(1) 
