
.TH DUB-LIST "1"

.SH NAME

dub\-list \- print a list of all local packages

.SH SYNOPSIS

.B dub list
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Prints a list of all local packages\&. This includes all cached packages (user
or system wide), all packages in the package search paths (see
\fIdub\-add\-path\fR(1)) and all manually registered packages (see
\fIdub\-add\-local\fR(1))\&.

.SH OPTIONS

This command supports all of the common options listed in \fIdub\fR(1)\&.

.SH SEE ALSO

\fIdub\fR(1), \fIdub\-add\-path\fR(1), \fIdub\-add\-local\fR(1)
