
.TH DUB-REMOVE-LOCAL "1"

.SH NAME

dub\-remove\-local \- remove a local package directory

.SH SYNOPSIS

.B dub remove\-local
.I PATH
[\fIOPTIONS\&.\&.\&.\fR]

.SH DESCRIPTION

Removes a local package directory previously added via \fBadd\-local\fR\&.

.SH OPTIONS

Apart of the options listed below, this command also honours common options 
listed in \fIdub\fR(1)\&.

.TP
.B \-\-system
Register system\-wide instead of user\-wide\&.

.SH SEE ALSO

\fIdub\fR(1), \fIdub\-add\-path\fR(1), \fIdub\-remove\-path\fR(1),
\fIdub\-add\-local\fR(1)
