/**
    Generator for Ninja build scripts

    License: Subject to the terms of the MIT license
    Authors: Hariprakash V
*/
module dub.generators.ninja;

import dub.compilers.compiler;
import dub.generators.generator;
import dub.project;

import std.algorithm : map, startsWith;
import std.array : join, replace;
import std.path : stripExtension;
import std.stdio : File;

class NinjaGenerator : ProjectGenerator
{
    this(Project project)
    {
        super(project);
    }

    override void generateTargets(GeneratorSettings settings, in TargetInfo[string] targets)
    {
        auto f = File("build.ninja", "w");
        scope(exit) f.close();

        immutable compiler = settings.platform.compilerBinary;
        immutable cname    = settings.platform.compiler;

        f.writeln("# Generated by DUB ninja generator");
        f.writeln();
        f.writeln("ar = ar");
        f.writeln();
        f.writeln("rule dc");
        f.writeln("  command = ", compiler, " $flags -c $in -of=$out");
        f.writeln("  description = Compiling $in");
        f.writeln();
        f.writeln("rule link");
        f.writeln("  command = ", compiler, " $in $lflags -of=$out");
        f.writeln("  description = Linking $out");
        f.writeln();
        f.writeln("rule ar");
        f.writeln("  command = $ar rcs $out $in");
        f.writeln("  description = Archiving $out");
        f.writeln();

        foreach (name, info; targets)
        {
            auto bs = info.buildSettings;

            auto importFlags  = bs.importPaths.map!(p => "-I" ~ p).join(" ");
            auto versionFlags = bs.versions.map!(v => versionFlag(cname) ~ v).join(" ");
            auto debugFlags   = bs.debugVersions.map!(v => debugFlag(cname) ~ v).join(" ");
            auto extraFlags   = bs.dflags.join(" ");

            string[] parts;
            if (importFlags.length)  parts ~= importFlags;
            if (versionFlags.length) parts ~= versionFlags;
            if (debugFlags.length)   parts ~= debugFlags;
            if (extraFlags.length)   parts ~= extraFlags;
            auto flags = parts.join(" ");

            auto lflags = bs.lflags.join(" ");

            string[] objs;
            foreach (src; bs.sourceFiles)
            {
                auto obj = objName(src);
                f.writeln("build ", obj, ": dc ", src);
                if (flags.length)
                    f.writeln("  flags = ", flags);
                objs ~= obj;
            }
            f.writeln();

            string[] depLibs;
            foreach (dep; info.linkDependencies)
            {
                if (dep in targets)
                    depLibs ~= libName(targets[dep].buildSettings.targetName, sanitizeName(dep));
            }

            auto outBin = bs.targetName.length ? bs.targetName : sanitizeName(name);

            if (bs.targetType == TargetType.staticLibrary ||
                bs.targetType == TargetType.library)
            {
                f.writeln("build ", outBin ~ ".a", ": ar ", objs.join(" "));
            }
            else
            {
                auto linkInputs = (objs ~ depLibs).join(" ");
                f.writeln("build ", outBin, ": link ", linkInputs);
                if (lflags.length)
                    f.writeln("  lflags = ", lflags);
                f.writeln();
                f.writeln("default ", outBin);
            }
            f.writeln();
        }
    }

    private static string objName(string src)
    {
        return stripExtension(src)
            .replace("/", "_")
            .replace("\\", "_")
            .replace(":", "_") ~ ".o";
    }

    private static string libName(string targetName, string fallback)
    {
        auto base = targetName.length ? targetName : fallback;
        return base ~ ".a";
    }

    private static string versionFlag(string cname)
    {
        if (cname.startsWith("ldc")) return "--d-version=";
        if (cname.startsWith("gdc")) return "-fversion=";
        return "-version=";
    }

    private static string debugFlag(string cname)
    {
        if (cname.startsWith("ldc")) return "--d-debug=";
        if (cname.startsWith("gdc")) return "-fdebug=";
        return "-debug=";
    }
    private static string sanitizeName(string name)
    {
        return name.replace(":", "_").replace("/", "_");
    }

}
